// PRICE_LIST
export const GET_PRICE_LIST = 'PRICE_LIST/GET_PRICE_LIST'
export const SET_PRICE_LIST = 'PRICE_LIST/SET_PRICE_LIST'
export const CHANGE_PRICE_LIST_TITLE = 'PRICE_LIST/CHANGE_PRICE_LIST_TITLE'

// FIELDS
export const CREATE_FIELD = 'FIELDS/CREATE_FIELD'
export const EDIT_FIELD = 'FIELDS/EDIT_FIELD'
export const DELETE_FIELD = 'FIELDS/DELETE_FIELD'

//GROUPS
export const CREATE_GROUP = 'GROUPS/CREATE_GROUP'
export const EDIT_GROUP = 'FIELDS/EDIT_GROUP'
export const DELETE_GROUP = 'GROUPS/DELETE_GROUP'

