// MESSAGES
export const GET_MESSAGES = 'MESSAGES/GET_MESSAGES'
export const EDIT_MESSAGE = 'MESSAGES/EDIT_MESSAGE'
export const DELETE_MESSAGE = 'MESSAGES/DELETE_MESSAGE'
// STAFF
export const GET_STAFF = 'STAFF/GET_STAFF'
export const EDIT_EMPLOYEE = 'STAFF/EDIT_EMPLOYEE'
export const DELETE_EMPLOYEE = 'STAFF/DELETE_EMPLOYEE'
export const CREATE_EMPLOYEE = 'STAFF/CREATE_EMPLOYEE'
export const EMPLOYEE_IN_EDITING = 'STAFF/EMPLOYEE_IN_EDITING'
// GALLERY
export const GET_PHOTOS = 'STAFF/GET_PHOTOS'
export const EDIT_PHOTO = 'STAFF/EDIT_PHOTO'
export const DELETE_PHOTO = 'STAFF/DELETE_PHOTO'
export const CREATE_PHOTO = 'STAFF/CREATE_PHOTO'
// PRICE LIST
export const GET_PRICE_LIST = 'PRICE_LIST/GET_PRICE_LIST'
export const EDIT_PRICE_LIST = 'PRICE_LIST/EDIT_PRICE_LIST'
export const DELETE_PRICE_LIST = 'PRICE_LIST/DELETE_PRICE_LIST'
export const CREATE_PRICE_LIST = 'PRICE_LIST/CREATE_PRICE_LIST'
// DIFFERENT

